osx_image: xcode10.2
language: objective-c
sudo: required
env:
  global:
    - PROJECT="ReusableKit.xcodeproj"
    - SCHEME="ReusableKit-Package"
    - IOS_SDK="iphonesimulator12.2"
    - MACOS_SDK="macosx10.14"
    - TVOS_SDK="appletvsimulator12.2"
    - FRAMEWORK="ReusableKit"
  matrix:
    - SDK="$IOS_SDK"      DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.2"

before_script:
  - set -o pipefail
  - pod repo update
  - swift package generate-xcodeproj

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'ReusableKit'
